[colors]
author = "Chris Kempson"
name = "Atelierdune (light)"

[colors.bright]
black = "#7d7a68"
blue = "#6684e1"
cyan = "#1fad83"
green = "#60ac39"
magenta = "#b854d4"
red = "#d73737"
white = "#fefbec"
yellow = "#cfb017"

[colors.cursor]
cursor = "#6e6b5e"
text = "#fefbec"

[colors.normal]
black = "#20201d"
blue = "#6684e1"
cyan = "#1fad83"
green = "#60ac39"
magenta = "#b854d4"
red = "#d73737"
white = "#a6a28c"
yellow = "#cfb017"

[colors.primary]
background = "#fefbec"
foreground = "#6e6b5e"
