[colors]
author = "Chris Kempson"
name = "Atelierheath (dark)"

[colors.bright]
black = "#776977"
blue = "#516aec"
cyan = "#159393"
green = "#379a37"
magenta = "#7b59c0"
red = "#ca402b"
white = "#f7f3f7"
yellow = "#bb8a35"

[colors.cursor]
cursor = "#ab9bab"
text = "#1b181b"

[colors.normal]
black = "#1b181b"
blue = "#516aec"
cyan = "#159393"
green = "#379a37"
magenta = "#7b59c0"
red = "#ca402b"
white = "#ab9bab"
yellow = "#bb8a35"

[colors.primary]
background = "#1b181b"
foreground = "#ab9bab"
