[colors]
author = "Baskerville"
name = "Lost Woods"

[colors.bright]
black = "#5e5e5e"
blue = "#ff9fc9"
cyan = "#00ddf4"
green = "#24dfc4"
magenta = "#ffa7f6"
red = "#ffa59a"
white = "#ffffff"
yellow = "#73db95"

[colors.cursor]
cursor = "#919191"
text = "#000000"

[colors.normal]
black = "#303030"
blue = "#a43261"
cyan = "#007086"
green = "#00715d"
magenta = "#913e88"
red = "#a13a38"
white = "#c6c6c6"
yellow = "#006f32"

[colors.primary]
background = "#000000"
foreground = "#919191"
