[colors]
author = "Chris Kempson"
name = "Brewer (light)"

[colors.bright]
black = "#737475"
blue = "#3182bd"
cyan = "#80b1d3"
green = "#31a354"
magenta = "#756bb1"
red = "#e31a1c"
white = "#fcfdfe"
yellow = "#dca060"

[colors.cursor]
cursor = "#515253"
text = "#fcfdfe"

[colors.normal]
black = "#0c0d0e"
blue = "#3182bd"
cyan = "#80b1d3"
green = "#31a354"
magenta = "#756bb1"
red = "#e31a1c"
white = "#b7b8b9"
yellow = "#dca060"

[colors.primary]
background = "#fcfdfe"
foreground = "#515253"
