[colors]
author = "Chris Kempson"
name = "Chalk (light)"

[colors.bright]
black = "#505050"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#f5f5f5"
yellow = "#ddb26f"

[colors.cursor]
cursor = "#303030"
text = "#f5f5f5"

[colors.normal]
black = "#151515"
blue = "#6fc2ef"
cyan = "#12cfc0"
green = "#acc267"
magenta = "#e1a3ee"
red = "#fb9fb1"
white = "#d0d0d0"
yellow = "#ddb26f"

[colors.primary]
background = "#f5f5f5"
foreground = "#303030"
