[colors.bright]
black = "#3f4944"
blue = "#484d79"
cyan = "#b02f30"
green = "#237986"
magenta = "#c59820"
red = "#2a5491"
white = "#b5d8f6"
yellow = "#a03b1e"

[colors.cursor]
cursor = "#9ea7a6"
text = "#232c31"

[colors.normal]
black = "#232c31"
blue = "#484d79"
cyan = "#b02f30"
green = "#237986"
magenta = "#c59820"
red = "#2a5491"
white = "#9ea7a6"
yellow = "#a03b1e"

[colors.primary]
background = "#232c31"
foreground = "#9ea7a6"
