[colors]
author = "Chris Kempson"
name = "Default (dark)"

[colors.bright]
black = "#505050"
blue = "#6a9fb5"
cyan = "#75b5aa"
green = "#90a959"
magenta = "#aa759f"
red = "#ac4142"
white = "#f5f5f5"
yellow = "#f4bf75"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#6a9fb5"
cyan = "#75b5aa"
green = "#90a959"
magenta = "#aa759f"
red = "#ac4142"
white = "#d0d0d0"
yellow = "#f4bf75"

[colors.primary]
background = "#151515"
foreground = "#d0d0d0"
