[colors]
author = "Chris Kempson"
name = "Embers (dark)"

[colors.bright]
black = "#5a5047"
blue = "#6d5782"
cyan = "#576d82"
green = "#57826d"
magenta = "#82576d"
red = "#826d57"
white = "#dbd6d1"
yellow = "#6d8257"

[colors.cursor]
cursor = "#a39a90"
text = "#16130f"

[colors.normal]
black = "#16130f"
blue = "#6d5782"
cyan = "#576d82"
green = "#57826d"
magenta = "#82576d"
red = "#826d57"
white = "#a39a90"
yellow = "#6d8257"

[colors.primary]
background = "#16130f"
foreground = "#a39a90"
