[colors]
author = ""
name = "Epiphany"

[colors.bright]
black = "#656565"
blue = "#647396"
cyan = "#505b6c"
green = "#8ccd6c"
magenta = "#cdb4c9"
red = "#e85555"
white = "#c0c0c0"
yellow = "#c5d67d"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#565656"
blue = "#677088"
cyan = "#445362"
green = "#88ab77"
magenta = "#cdcdb4"
red = "#ac4f4f"
white = "#ffffff"
yellow = "#d0d9ad"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
