[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xcb2431"
index = 17

[colors.bright]
black = "0x586069"
blue = "0x2188ff"
cyan = "0x1b7c83"
green = "0x28a745"
magenta = "0x8a63d2"
red = "0xcb2431"
white = "0x4d5566"
yellow = "0xdbab09"

[colors.normal]
black = "0x24292e"
blue = "0x0366d6"
cyan = "0x1b7c83"
green = "0x22863a"
magenta = "0x6f42c1"
red = "0xd73a49"
white = "0x4d5566"
yellow = "0xb08800"

[colors.primary]
background = "0xffffff"
foreground = "0x4d5566"
