[colors]
author = "jmbi"
name = "jmbi"

[colors.bright]
black = "#8DA691"
blue = "#C9B957"
cyan = "#C25431"
green = "#CCC68D"
magenta = "#FFCBAB"
red = "#EEAA88"
white = "#F9F1ED"
yellow = "#EEDD99"

[colors.cursor]
cursor = "#ffffff"
text = "#1e1e1e"

[colors.normal]
black = "#5A7260"
blue = "#E0BA69"
cyan = "#D13516"
green = "#BBBB88"
magenta = "#709289"
red = "#8F423C"
white = "#EFE2E0"
yellow = "#F9D25B"

[colors.primary]
background = "#1e1e1e"
foreground = "#ffffff"
