[colors]
author = "Chris Kempson"
name = "Londontube (light)"

[colors.bright]
black = "#737171"
blue = "#009ddc"
cyan = "#85cebc"
green = "#00853e"
magenta = "#98005d"
red = "#ee2e24"
white = "#ffffff"
yellow = "#ffd204"

[colors.cursor]
cursor = "#5a5758"
text = "#ffffff"

[colors.normal]
black = "#231f20"
blue = "#009ddc"
cyan = "#85cebc"
green = "#00853e"
magenta = "#98005d"
red = "#ee2e24"
white = "#d9d8d8"
yellow = "#ffd204"

[colors.primary]
background = "#ffffff"
foreground = "#5a5758"
