[colors.bright]
black = "#4f362b"
blue = "#8ca8a3"
cyan = "#a167c7"
green = "#6cb87a"
magenta = "#ffa64f"
red = "#da4375"
white = "#fdfdfd"
yellow = "#e3da84"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#2a1d17"
blue = "#3ea290"
cyan = "#8c16da"
green = "#3ea250"
magenta = "#ff850d"
red = "#da1657"
white = "#e9e9e9"
yellow = "#e3d33d"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
