[colors]
author = "Chris Kempson"
name = "Mocha (dark)"

[colors.bright]
black = "#7e705a"
blue = "#8ab3b5"
cyan = "#7bbda4"
green = "#beb55b"
magenta = "#a89bb9"
red = "#cb6077"
white = "#f5eeeb"
yellow = "#f4bc87"

[colors.cursor]
cursor = "#d0c8c6"
text = "#3b3228"

[colors.normal]
black = "#3b3228"
blue = "#8ab3b5"
cyan = "#7bbda4"
green = "#beb55b"
magenta = "#a89bb9"
red = "#cb6077"
white = "#d0c8c6"
yellow = "#f4bc87"

[colors.primary]
background = "#3b3228"
foreground = "#d0c8c6"
