[colors]
author = "Muzieca"
name = "Low Contrast"

[colors.bright]
black = "#828282"
blue = "#8f99d9"
cyan = "#8fd9d5"
green = "#b8d98f"
magenta = "#b08fd9"
red = "#d98f93"
white = "#c5c5c5"
yellow = "#d9cf8f"

[colors.cursor]
cursor = "#93a1a1"
text = "#3c3b37"

[colors.normal]
black = "#5f5f5f"
blue = "#64a2d9"
cyan = "#64d9d5"
green = "#a2d964"
magenta = "#9a64d9"
red = "#d96468"
white = "#989898"
yellow = "#d9c964"

[colors.primary]
background = "#3c3b37"
foreground = "#93a1a1"
