[colors.bright]
black = "#8ca8a6"
blue = "#415c77"
cyan = "#3a6868"
green = "#28634d"
magenta = "#532706"
red = "#a24b76"
white = "#330801"
yellow = "#9d5823"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#658280"
blue = "#304465"
cyan = "#175552"
green = "#184a31"
magenta = "#330801"
red = "#822f5d"
white = "#110005"
yellow = "#9d4500"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
