[colors]
author = ""
name = "Numix Darkest"

[colors.bright]
black = "#888888"
blue = "#0f75bd"
cyan = "#37c3d6"
green = "#86df5d"
magenta = "#9e5e83"
red = "#d64937"
white = "#f9f9f9"
yellow = "#fdd75a"

[colors.cursor]
cursor = "#a2a2a2"
text = "#282828"

[colors.normal]
black = "#555555"
blue = "#0d68a8"
cyan = "#288e9c"
green = "#61bc3b"
magenta = "#744560"
red = "#9c3528"
white = "#a2a2a2"
yellow = "#f3b43a"

[colors.primary]
background = "#282828"
foreground = "#a2a2a2"
