[colors]
author = "Chris Kempson"
name = "Paraiso (light)"

[colors.bright]
black = "#776e71"
blue = "#06b6ef"
cyan = "#5bc4bf"
green = "#48b685"
magenta = "#815ba4"
red = "#ef6155"
white = "#e7e9db"
yellow = "#fec418"

[colors.cursor]
cursor = "#4f424c"
text = "#e7e9db"

[colors.normal]
black = "#2f1e2e"
blue = "#06b6ef"
cyan = "#5bc4bf"
green = "#48b685"
magenta = "#815ba4"
red = "#ef6155"
white = "#a39e9b"
yellow = "#fec418"

[colors.primary]
background = "#e7e9db"
foreground = "#4f424c"
