[colors.bright]
black = "#86817e"
blue = "#68778c"
cyan = "#86abd9"
green = "#688c7d"
magenta = "#8c686a"
red = "#a63a3a"
white = "#f7f8f2"
yellow = "#ffb365"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#86817e"
blue = "#68778c"
cyan = "#86abd9"
green = "#688c7d"
magenta = "#fdb3b2"
red = "#d75756"
white = "#f7f8f2"
yellow = "#ffb365"

[colors.primary]
background = "#000000"
foreground = "#ffffff"
