[colors.bright]
black = "#5a647e"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#a5c261"
magenta = "#b6b3eb"
red = "#da4939"
white = "#f9f7f3"
yellow = "#ffc66d"

[colors.cursor]
cursor = "#3a4055"
text = "#f9f7f3"

[colors.normal]
black = "#2b2b2b"
blue = "#6d9cbe"
cyan = "#519f50"
green = "#a5c261"
magenta = "#b6b3eb"
red = "#da4939"
white = "#e6e1dc"
yellow = "#ffc66d"

[colors.primary]
background = "#f9f7f3"
foreground = "#3a4055"
