[colors.bright]
black = "#0b141a"
blue = "#0099ff"
cyan = "#00a5ab"
green = "#11ab00"
magenta = "#9854ff"
red = "#ff4053"
white = "#ffffff"
yellow = "#bf8c00"

[colors.normal]
black = "#0b141a"
blue = "#0099ff"
cyan = "#00a5ab"
green = "#11ab00"
magenta = "#9854ff"
red = "#ff4053"
white = "#ffffff"
yellow = "#bf8c00"

[colors.primary]
background = "#ffffff"
foreground = "#61707a"
