[colors.bright]
black = "#383332"
blue = "#65788F"
cyan = "#718062"
green = "#898471"
magenta = "#755E4A"
red = "#8C4F4A"
white = "#BC9D66"
yellow = "#C8B491"

[colors.cursor]
cursor = "#DABA8B"
text = "#191716"

[colors.normal]
black = "#0F0E0D"
blue = "#43454F"
cyan = "#5C6652"
green = "#57553C"
magenta = "#604848"
red = "#845336"
white = "#A18B62"
yellow = "#A17E3E"

[colors.primary]
background = "#191716"
foreground = "#DABA8B"
