[colors.bright]
black = "#5f5a60"
blue = "#7587a6"
cyan = "#afc4db"
green = "#8f9d6a"
magenta = "#9b859d"
red = "#cf6a4c"
white = "#ffffff"
yellow = "#f9ee98"

[colors.cursor]
cursor = "#a7a7a7"
text = "#1e1e1e"

[colors.normal]
black = "#1e1e1e"
blue = "#7587a6"
cyan = "#afc4db"
green = "#8f9d6a"
magenta = "#9b859d"
red = "#cf6a4c"
white = "#a7a7a7"
yellow = "#f9ee98"

[colors.primary]
background = "#1e1e1e"
foreground = "#a7a7a7"
