[colors.bright]
black = "#606060"
blue = "#7491a1"
cyan = "#0f829d"
green = "#a7b79a"
magenta = "#87314e"
red = "#d14548"
white = "#fff0f0"
yellow = "#fae3a0"

[colors.cursor]
cursor = "#d2c5bc"
text = "#101010"

[colors.normal]
black = "#202020"
blue = "#356579"
cyan = "#0b3452"
green = "#81957c"
magenta = "#2d2031"
red = "#b91e2e"
white = "#909090"
yellow = "#f9bb80"

[colors.primary]
background = "#101010"
foreground = "#d2c5bc"
