[colors.bright]
black = "#7F7F7A"
blue = "#5986B2"
cyan = "#F2854A"
green = "#664233"
magenta = "#D9AE98"
red = "#B23636"
white = "#4C4742"
yellow = "#BF8F60"

[colors.cursor]
cursor = "#34302D"
text = "#F5E7DE"

[colors.normal]
black = "#666661"
blue = "#4C7399"
cyan = "#D97742"
green = "#4C3226"
magenta = "#BF9986"
red = "#992E2E"
white = "#34302D"
yellow = "#A67C53"

[colors.primary]
background = "#F5E7DE"
foreground = "#34302D"
