name: CI

on:
  push:
    branches: [main]

jobs:
  init-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          check-latest: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Go test

        run: |
          echo "Go test"
          go test ./... -coverprofile coverage.out -covermode count


      - name: Go check coverage
        env:
          TESTCOVERAGE_THRESHOLD: 85
          TESTCOVERAGE_TIMEOUT: 60s
        run: |
          echo "Go: Checking go test coverage"
          echo "Threshold : $TESTCOVERAGE_THRESHOLD %"
          total_coverage=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
          echo "Test coverage: $total_coverage %"

          if (( $(echo "$total_coverage $TESTCOVERAGE_THRESHOLD" | awk '{print($1 > $2)}') )); then
            echo "OK"
          else
            echo "Test coverage low $total_coverage"
            echo "Failed"
            exit 1
          fi
